permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
advanced:
  pan_id: 6755
  network_key:
    - 163
    - 63
    - 171
    - 115
    - 2
    - 58
    - 120
    - 247
    - 15
    - 190
    - 98
    - 56
    - 143
    - 223
    - 187
    - 149
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0xcc86ecfffe327b56':
    friendly_name: '0xcc86ecfffe327b56'
