version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
  zigbee_controller:
    depends_on:
      - mqtt
    container_name: zbc
    build: ./zigbee_controller
    ports:
      - 8888:9999
    volumes:
      - ./zigbee_controller:/app
    restart: unless-stopped
    command: uvicorn main:app --log-level info --port 9999 --host "0.0.0.0" --workers 1 --reload
